// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/hello': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hello').default>>>>
    }
    '/api/products/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[id]/index').default>>>>
    }
    '/api/products/categories': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/categories').default>>>>
    }
    '/api/products/category/:category': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/category/[category]/index').default>>>>
    }
    '/api/products': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/index').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}